export const expenseCalculator = {
  GET_DISEASE_COST_FILTER_SUCCESS: 'GET_DISEASE_COST_FILTER_SUCCESS',
  GET_DISEASE_COST_FILTER_FAIL: 'GET_DISEASE_COST_FILTER_FAIL',
  SET_DISEASE_PANEL_DATA: 'SET_DISEASE_PANEL_DATA', // 设置疾病面板数据
  SET_LOCATION_PANEL_DATA: 'SET_LOCATION_PANEL_DATA', // 设置城市信息
  SET_SBTYPE_SELECTION: 'SET_SBTYPE_SELECTION', // 设置社保类型选择方案
  SET_CBTYPE_SELECTION: 'SET_CBTYPE_SELECTION' // 设置参保类型选择方案
}

export const doctorSearch = {
  SET_HOSPITAL_SEARCH_FILTER: 'SET_HOSPITAL_SEARCH_FILTER', // 设置医院查询过滤器
  SET_HOSPITAL_SEARCH_LIST: 'SET_HOSPITAL_SEARCH_LIST', // 设置医院查询结果列表
  SET_HOSPITAL_INFO: 'SET_HOSPITAL_INFO', // 设置医院详细信息
  SET_CONSULTANT_LIST: 'SET_CONSULTANT_LIST',
  SET_DOCTOR_SEARCH_FILTER: 'SET_DOCTOR_SEARCH_FILTER', // 设置医生查询过滤器
  SET_DOCTOR_SEARCH_LIST: 'SET_DOCTOR_SEARCH_LIST', // 设置医生列表
  SET_DOCTOR_SEARCH_LIST_BY_FILTER: 'SET_DOCTOR_SEARCH_LIST_BY_FILTER', // 设置过滤后的医生列表
  SET_LOCATION_PANEL_DATA: 'SET_LOCATION_PANEL_DATA' // 设置城市列表

}

export const appSearch = {
  SHOW_MINI: 'SHOW_MINI',
  HIDE_MINI: 'HIDE_MINI',
  SET_HOT_LIST: 'SET_HOT_LIST',
  SET_HOT_LIST_TYPE: 'SET_HOT_LIST_TYPE',
  SET_HISTORY_LIST: 'SET_HISTORY_LIST',
  SET_ASSOCIATE_LIST: 'SET_ASSOCIATE_LIST',
  CLEAR_HISTORY: 'CLEAR_HISTORY'
}

export const app = {
  SET_SEARCHER: 'SET_SEARCHER'
}
